component_depth: 1
languages:
  - name: cpp
    production:
      include:
        - /exe/.*\.cpp
      exclude:
        - /cmake/.*
        - /docs/.*
        - /scripts/.*
        - /test/.*
        - /vcpkg/.*
    test:
      include:
        - /test/.*\.cpp
      exclude:
        - /cmake/.*
        - /docs/.*
        - /scripts/.*
        - /vcpkg/.*
