name: Build python wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

env:
  CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
  CIBW_ARCHS: auto64
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_BEFORE_ALL_MACOS: brew install autoconf-archive
  CIBW_BEFORE_ALL_LINUX: yum install autoconf-archive
  CIBW_BEFORE_BUILD: pip install --upgrade pip setuptools wheel ninja numpy cython
  CIBW_BEFORE_BUILD_WINDOWS: "{project}\vcpkg\bootstrap-vcpkg.bat & {project}\vcpkg\vcpkg install yasm-tool:x86-windows"
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  upload_all:
    name: Upload to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/setup-python@v2

      - name: Download wheels
        uses: actions/download-artifact@v1
        with:
          name: wheels

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: wheels/
