name: Build python wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

env:
  CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
  CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
  CIBW_ARCHS_LINUX: auto64
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_BEFORE_ALL_MACOS: brew install libomp pkg-config automake autoconf autoconf-archive libtool
  CIBW_BEFORE_BUILD: pip install --upgrade pip setuptools wheel ninja numpy cython
  CIBW_ENVIRONMENT_MACOS: CXX="$(brew --prefix llvm@15)/bin/clang++"
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  upload_all:
    name: Upload to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/setup-python@v3

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: wheels/
