name: regression test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Test decoding quantities can be generated
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-${{ hashFiles('scripts/vcpkg_dependencies', 'vcpkg/CHANGELOG.md') }}

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install system dependencies
        run: |
          sudo apt install libgmp-dev libmpfr-dev libgsl0-dev

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cython numpy
          python -m pip install .
        env:
          CXX: g++-10

      - name: compile prepare decoding
        run: |
          mkdir build_dir && cd build_dir
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel 2 --target prepare_decoding_exe
        env:
          CXX: g++-10

      - name: generate & check decoding quantities
        run: |
          bash test_prepare.sh ../../build_dir/exe/prepare_decoding_exe
        working-directory: test/regression
