name: Sanitiser checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Sanitiser checks
    runs-on: ubuntu-20.04
    env:
      CXX: clang++-10

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            vcpkg/
            build_dir/vcpkg_installed/
          key: ${{ runner.os }}-${{ env.CXX }}-${{ hashFiles('vcpkg.json', 'vcpkg/CHANGELOG.md') }}

      - name: make build directory
        run: mkdir build_dir
        if: steps.cache.outputs.cache-hit != 'true'

      - name: address sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_ADDRESS=ON
          cmake --build . --parallel 2 --target unit_tests
          ./test/unit_tests ~"Test prepare decoding"
        working-directory: build_dir

      - name: leak sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_LEAK=ON
          cmake --build . --parallel 2 --target unit_tests
          ./test/unit_tests
        working-directory: build_dir

      - name: undefined behaviour sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_UNDEFINED_BEHAVIOUR=ON
          cmake --build . --parallel 2 --target unit_tests
          ./test/unit_tests
        working-directory: build_dir

      - name: thread sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_THREAD=ON
          cmake --build . --parallel 2 --target unit_tests
          ./test/unit_tests ~"Test prepare decoding"
        working-directory: build_dir
