name: Sanitiser checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Sanitiser checks
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-18

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: make build directory
        run: mkdir build_dir

      - name: address sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_ADDRESS=ON
          cmake --build . --parallel 4 --target unit_tests
          ./test/unit_tests ~"Test prepare decoding"
        working-directory: build_dir

      - name: leak sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_LEAK=ON
          cmake --build . --parallel 4 --target unit_tests
          ./test/unit_tests
        working-directory: build_dir

      - name: undefined behaviour sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_UNDEFINED_BEHAVIOUR=ON
          cmake --build . --parallel 4 --target unit_tests
          ./test/unit_tests
        working-directory: build_dir

      - name: thread sanitiser
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITISER_THREAD=ON
          cmake --build . --parallel 4 --target unit_tests
          ./test/unit_tests ~"Test prepare decoding"
        working-directory: build_dir
