name: Static analysis checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Static analysis checks
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-18

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: make build directory
        run: mkdir build_dir

      - name: install analysers
        run: |
          sudo apt -y install cppcheck

      - name: compile with cppcheck
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CPPCHECK=ON
          cmake --build . --parallel 2 --target prepare_decoding_lib prepare_decoding_exe
        working-directory: build_dir

      - name: compile with clang tidy
        run: |
          mv vcpkg_installed .. && rm -rf * && mv ../vcpkg_installed .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CLANG_TIDY=ON
          cmake --build . --parallel 2 --target prepare_decoding_lib prepare_decoding_exe
        working-directory: build_dir
