name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit tests on Ubuntu
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo & vcpkg submodule
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-${{ hashFiles('scripts/vcpkg_dependencies') }}

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install analysers
        run: sudo apt install cppcheck

      - name: make build directories
        run: |
          mkdir cppcheck_dir
          mkdir clang_tidy_dir

      - name: compile with cppcheck
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CPPCHECK=ON
          cmake --build . --parallel 2 --target prepare_decoding_lib prepare_decoding_exe
        working-directory: cppcheck_dir
        env:
          CXX: clang++-9

      - name: compile with clang tidy
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CLANG_TIDY=ON
          cmake --build . --parallel 2 --target prepare_decoding_lib prepare_decoding_exe
        working-directory: cppcheck_dir
        env:
          CXX: clang++-9
