name: "Unit tests: Ubuntu"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit tests on Ubuntu
    runs-on: ubuntu-24.04
    env:
      CXX: g++-13

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 4 --target unit_tests
        working-directory: build_dir

      - name: cmake test
        run: ctest -j4 --output-on-failure
        working-directory: build_dir
