name: "Unit tests: Windows"

on:
  push:
    branches:
      - none
  pull_request:
    branches:
      - none

jobs:

  build-and-test:
    name: Unit tests on Windows
    runs-on: windows-latest

    steps:

      - name: checkout repo & vcpkg submodule
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            vcpkg/
            build_dir/vcpkg_installed/
          key: ${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg/CHANGELOG.md') }}

      - name: make build directory
        run: |
          mkdir build_dir
          mkdir build_dir\vcpkg_installed
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install system packages
        run: |
          .\bootstrap-vcpkg.bat
          .\vcpkg --x-install-root=${{ github.workspace }}\build_dir\vcpkg_installed install yasm-tool:x86-windows
        working-directory: vcpkg

      - name: cmake configure
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target unit_tests
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir
