name: Build wheels

on:
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  CIBW_BUILD: cp38-*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-${{ hashFiles('scripts/vcpkg_dependencies', 'vcpkg/CHANGELOG.md') }}

      - name: install dependencies macOS & linux
        run: |
          bash scripts/install_dependencies.sh
        if: steps.cache.outputs.cache-hit != 'true' && matrix.os != 'windows-2019'

      - name: install dependencies Windows
        run: |
          scripts/install_dependencies.bat
        if: steps.cache.outputs.cache-hit != 'true' && matrix.os == 'windows-2019'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
