name: Build wheels

on:
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  CIBW_BUILD: cp38-*
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014
  CIBW_BEFORE_BUILD: pip install --upgrade pip setuptools wheel numpy cython
  CIBW_BEFORE_BUILD_LINUX: bash scripts/install_dependencies.sh
  CIBW_BEFORE_BUILD_MACOS: bash scripts/install_dependencies.sh
  CIBW_BEFORE_BUILD_WINDOWS: scripts/install_dependencies.bat

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
